export const EXTRA_SERVICES = [
    { id: "none", name: "None", description: "No additional services" },
    { id: "parking", name: "Parking Spot", description: "Secure on-site parking" },
    { id: "food_delivery", name: "Food-To-Room Delivery", description: "In-room dining service" },
    { id: "airport_shuttle", name: "Airport Shuttle", description: "Transport to and from the airport" },
    { id: "fitness_center", name: "Fitness Center Access", description: "Access to the fitness center" },
    { id: "laundry", name: "Laundry and Dry-Cleaning", description: "Laundry and dry-cleaning service" },
    { id: "wake_up_call", name: "Wake-up Call Service", description: "Personalized wake-up call service" },
    { id: "wifi", name: "Wi-Fi", description: "High-speed internet access" },
    { id: "breakfast", name: "Breakfast", description: "Daily continental breakfast" },
    { id: "spa", name: "Spa Access", description: "Access to spa and wellness facilities" },
    { id: "pet_care", name: "Pet Care", description: "Pet-sitting and walking services" },
    { id: "late_checkout", name: "Late Checkout", description: "Extended checkout time" },
    { id: "childcare", name: "Childcare", description: "Babysitting and childcare services" },
    { id: "mini_bar", name: "Mini Bar", description: "Stocked in-room mini bar" },
    { id: "room_service", name: "Room Service", description: "24/7 in-room food and beverage service" },
];
